services:

  app:
    build: app
    ports:
      - 8000:8000
    depends_on:
      - mongo
      - mariadb
    develop:
      watch:
        - action: sync+restart
          path: app/src
          target: /app/src
        - action: rebuild
          path: app/Dockerfile
        - action: rebuild
          path: app/requirements.txt

  mongo:
    image: mongo
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_US}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PWD}
    volumes:
      - mongo_data:/data/db

  mariadb:
    image: mariadb:lts-jammy
    restart: always
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=app

volumes:
  mongo_data:


